service:
  name: movies-list-microservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    REDIS_HOST: redis-12555.c212.ap-south-1-1.ec2.cloud.redislabs.com
    REDIS_PORT: 12555
    REDIS_PASSWORD: ZtW0Td51cI2kEsJNEnpFz6N2y1isaBsh

functions:
  listMovies:
    handler: src/handler.moviesListHandler
    events:
      - http:
          method: get
          path: movies/search
          cors: true
  searchMovies:
    # handler: src/handler.moviesGroupByHandler
    handler: src/handler.moviesGroupByHandler
    events:
      - http:
          method: get
          path: movies/group_by/{field}
          cors: true
  getMovie:
    handler: src/handler.moviesGetHandler
    events:
      - http:
          method: get
          path: movies/{id}
          cors: true
