service:
  name: movies-list-microservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    REDIS_HOST: redis-17106.c239.us-east-1-2.ec2.cloud.redislabs.com
    REDIS_PORT: 17106
    REDIS_PASSWORD: IdEOtZyRxzxwNXqYmqRla4XrPAqUqw3o

functions:
  listMovies:
    handler: src/handler.moviesListHandler
    events:
      - http:
          method: get
          path: movies
  getMovie:
    handler: src/handler.moviesGetHandler
    events:
      - http:
          method: get
          path: movies/{id}
